name: 'Setup Foreman'
description: 'Install Foreman, a toolchain manager for Roblox projects'
author: 'The Rojo Developers'
inputs:
  version:
    description: 'SemVer version of Foreman to install'
runs:
  using: 'node12'
  main: 'dist/index.js'
