name: "build-test"

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
      npm install
      npm run all
    - uses: ./
      with:
        version: "^0.5.0"