name: "build-test"

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run all
    - run: npm run pack
    - uses: ./
      with:
        version: "^0.5.0"
        token: ${{ secrets.GITHUB_TOKEN }}